package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class InventoryReceiptAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryReceiptAllPropertiesEquals(InventoryReceipt expected, InventoryReceipt actual) {
        assertInventoryReceiptAutoGeneratedPropertiesEquals(expected, actual);
        assertInventoryReceiptAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryReceiptAllUpdatablePropertiesEquals(InventoryReceipt expected, InventoryReceipt actual) {
        assertInventoryReceiptUpdatableFieldsEquals(expected, actual);
        assertInventoryReceiptUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryReceiptAutoGeneratedPropertiesEquals(InventoryReceipt expected, InventoryReceipt actual) {
        assertThat(actual)
            .as("Verify InventoryReceipt auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryReceiptUpdatableFieldsEquals(InventoryReceipt expected, InventoryReceipt actual) {
        assertThat(actual)
            .as("Verify InventoryReceipt relevant properties")
            .satisfies(a -> assertThat(a.getReceiptDate()).as("check receiptDate").isEqualTo(expected.getReceiptDate()))
            .satisfies(a ->
                assertThat(a.getTotalAmount())
                    .as("check totalAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalAmount())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryReceiptUpdatableRelationshipsEquals(InventoryReceipt expected, InventoryReceipt actual) {
        // empty method
    }
}
