package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ReceiptDetailAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReceiptDetailAllPropertiesEquals(ReceiptDetail expected, ReceiptDetail actual) {
        assertReceiptDetailAutoGeneratedPropertiesEquals(expected, actual);
        assertReceiptDetailAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReceiptDetailAllUpdatablePropertiesEquals(ReceiptDetail expected, ReceiptDetail actual) {
        assertReceiptDetailUpdatableFieldsEquals(expected, actual);
        assertReceiptDetailUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReceiptDetailAutoGeneratedPropertiesEquals(ReceiptDetail expected, ReceiptDetail actual) {
        assertThat(actual)
            .as("Verify ReceiptDetail auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReceiptDetailUpdatableFieldsEquals(ReceiptDetail expected, ReceiptDetail actual) {
        assertThat(actual)
            .as("Verify ReceiptDetail relevant properties")
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()))
            .satisfies(a ->
                assertThat(a.getPurchasePrice())
                    .as("check purchasePrice")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPurchasePrice())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReceiptDetailUpdatableRelationshipsEquals(ReceiptDetail expected, ReceiptDetail actual) {
        assertThat(actual)
            .as("Verify ReceiptDetail relationships")
            .satisfies(a -> assertThat(a.getReceipt()).as("check receipt").isEqualTo(expected.getReceipt()))
            .satisfies(a -> assertThat(a.getBook()).as("check book").isEqualTo(expected.getBook()));
    }
}
